# Generated by Django 5.1.6 on 2025-11-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('users', '0002_alter_user_id'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments_votes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.CharField(default='upvote', max_length=7)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
