# Generated by Django 5.1.6 on 2025-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_comments_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_votes',
            name='vote',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='votes',
            name='vote',
            field=models.CharField(max_length=8),
        ),
    ]
