# Generated by Django 5.1.6 on 2025-11-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiservice', '0001_initial'),
        ('resources', '0006_delete_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_saved_answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
                ('Resource', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
    ]
