# Generated by Django 5.1.6 on 2025-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_saved_answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
            ],
        ),
    ]
