# Generated by Django 5.1.6 on 2025-11-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiservice', '0002_ai_saved_answer'),
        ('resources', '0006_delete_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_saved_answer',
            name='Resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
    ]
