# Generated by Django 5.1.6 on 2025-11-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiservice', '0003_alter_ai_saved_answer_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_saved_answer',
            old_name='Resource',
            new_name='resource',
        ),
    ]
