# Generated by Django 5.1.6 on 2025-11-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
