# Generated by Django 5.1.6 on 2025-11-15 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_summary',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='resources.resource'),
        ),
    ]
