# Generated by Django 5.1.6 on 2025-11-15 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_ai_summary_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_summary',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
    ]
