# Generated by Django 5.1.6 on 2025-11-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_ai_summary_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ai_summary',
        ),
    ]
